begin;
select plan(15);
select has_table('public','commercial_kiosk_registrations','commercial kiosk registrations exist');
select has_table('public','commercial_kiosk_claim_attempts','claim attempts exist');
select has_column('public','kiosk_devices','registration_id','devices reference registration evidence');
select has_column('public','kiosk_devices','last_heartbeat_at','devices retain privacy-safe heartbeat evidence');
select has_column('public','kiosk_devices','roster_verified_at','devices retain roster verification evidence');
select has_function('public','claim_commercial_kiosk',array['uuid','text','text'],'claim RPC exists');
select has_function('public','record_commercial_kiosk_heartbeat',array['text','text','integer','text'],'heartbeat RPC exists');
select has_function('public','verify_commercial_kiosk_roster',array['text'],'minimal roster verification RPC exists');
select lives_ok($$select public.claim_commercial_kiosk(null,'BAD','short')$$,'invalid anonymous claim fails safely');
select is((select public.claim_commercial_kiosk(null,'BAD','short')->>'outcome'),'invalid_code','invalid claim exposes only stable code');
select is((select count(*)::int from information_schema.role_table_grants where table_schema='public' and table_name='commercial_kiosk_claim_attempts' and grantee in('anon','authenticated') and privilege_type in('INSERT','UPDATE','DELETE')),0,'clients cannot mutate claim attempts');
select is((select count(*)::int from information_schema.role_routine_grants where routine_schema='private' and routine_name in('commercial_kiosk_snapshot','execute_kiosk_onboarding_command') and grantee in('PUBLIC','anon','authenticated')),0,'private kiosk definers are not executable');
select is((select count(*)::int from public.kiosk_devices where organisation_id is not null and offline_enabled),0,'commercial kiosk devices remain offline-disabled');
select is((select count(*)::int from public.kiosk_offline_authorisations a join public.kiosk_devices d on d.id=a.kiosk_device_id where d.organisation_id is not null and a.revoked_at is null),0,'commercial kiosks have no offline authorisation');
select is((select count(*)::int from public.clock_events e join public.kiosk_devices d on d.id=e.kiosk_device_uuid where d.registration_id is not null),0,'registration creates no attendance evidence');
select * from finish();
rollback;
