import type { PGlite } from "@electric-sql/pglite";
import { createHash } from "node:crypto";
import { afterEach, beforeEach, describe, expect, it } from "vitest";
import { USER_A_OWNER, USER_B_OWNER, resetTenantDatabaseRole, setTenantAuthUser } from "./helpers/tenant-primitives-db";
import { createInitialStaffingOnboardingDatabase } from "./helpers/onboarding-persistence-db";

type Snapshot = { session:{id:string;organisationId:string|null;revision:string;currentStepKey:string}; legalDocuments:Array<{documentType:string;documentVersion:string;locale:string}>;
  steps:Array<{stepKey:string;status:string;draftPayload:Record<string,unknown>}>;
  staffing:{activeStaffCount:number;staffLimit:number|null;activeBatch:null|{id:string;status:string;rows:Array<{id:string;decision:string;validationCodes:string[]}>}} };
const keys = ["64000000-0000-4000-8000-000000000001","64000000-0000-4000-8000-000000000002","64000000-0000-4000-8000-000000000003","64000000-0000-4000-8000-000000000004"];
async function load(db:PGlite){return (await db.query<{x:Snapshot}>("select public.get_or_create_onboarding_bootstrap() x")).rows[0].x;}
function env(s:Snapshot,type:string,key:string,payload:unknown){return {schemaVersion:1,workflowKey:"commercial_customer_v1",workflowVersion:1,sessionId:s.session.id,commandType:type,idempotencyKey:key,expectedSessionRevision:s.session.revision,payload};}
function reviewedHash(rows:Array<{id:string;decision:string}>){const value=rows.map(r=>`${r.id}:${r.decision}`).sort().join(",");return createHash("md5").update(value).digest("hex")+createHash("md5").update(`sha256:${value}`).digest("hex");}
async function exec(db:PGlite,e:unknown){return (await db.query<{x:{commandResult:{outcome:string;resultCode:string};bootstrap:Snapshot} }>("select public.execute_onboarding_bootstrap_command($1::jsonb) x",[JSON.stringify(e)])).rows[0].x;}
async function ready(db:PGlite){let s=await load(db);s=(await exec(db,env(s,"accept_legal_documents",keys[0],{acceptances:s.legalDocuments.map(d=>({documentType:d.documentType,documentVersion:d.documentVersion,locale:d.locale})),safeRequestMetadata:{source:"commercial_onboarding"}}))).bootstrap;
  s=(await exec(db,env(s,"create_organisation",keys[1],{displayName:"Northstar Demo",legalName:"Northstar Demo Limited",contactEmail:"owner@example.invalid",country:"GB",timezone:"Europe/London",postalAddress:{line1:"1 Fictional Way",locality:"Exampleton",postcode:"ZZ1 1ZZ"}}))).bootstrap;
  s=(await exec(db,env(s,"create_first_site",keys[2],{siteName:"Northstar Central",contactPhone:"+44 20 7946 0999",country:"GB",timezone:"Europe/London",postalAddress:{line1:"2 Fictional Way",locality:"Exampleton",postcode:"ZZ1 1ZZ"},openingHours:Array.from({length:7},(_,i)=>({dayOfWeek:i+1,intervals:i<5?[{opensAt:"08:00",closesAt:"18:00"}]:[]})),workWeekStarts:1,operationalDayBoundary:"04:00"}))).bootstrap;
  return (await exec(db,env(s,"select_plan",keys[3],{planKey:"preview_standard",planVersion:1,selection:"free_trial"}))).bootstrap;}

describe("commercial initial staffing database",()=>{let db:PGlite;beforeEach(async()=>{db=await createInitialStaffingOnboardingDatabase();await setTenantAuthUser(db,USER_A_OWNER,"aal2");},30000);afterEach(async()=>db?.close());
  it("atomically creates a manual staff profile, first-site assignment and disabled PIN-pending settings",async()=>{const s=await ready(db);const drafted=await exec(db,env(s,"save_staff_draft","64000000-0000-4000-8000-000000000009",{fullName:"Alex",attendanceEligible:true}));expect(drafted.bootstrap.steps.find(step=>step.stepKey==="staffing")?.draftPayload).toMatchObject({fullName:"Alex"});
    const staff={externalStaffId:"EMP-001",fullName:"Alex Morgan",displayName:"Alex",email:"alex@example.invalid",employmentStatus:"active",startDate:"2026-09-01",jobRole:"staff",attendanceEligible:true};const command=env(drafted.bootstrap,"create_staff","64000000-0000-4000-8000-000000000010",staff);
    const first=await exec(db,command);const replay=await exec(db,command);expect(first.commandResult.resultCode).toBe("staff_manual_created");expect(replay.commandResult.outcome).toBe("replayed");await setTenantAuthUser(db,USER_A_OWNER,"aal1");const deniedReplay=await exec(db,command);expect(deniedReplay.commandResult.resultCode).toBe("mfa_required");expect(deniedReplay.bootstrap).toBeNull();await setTenantAuthUser(db,USER_A_OWNER,"aal2");
    const changed=await exec(db,{...command,payload:{...staff,displayName:"Changed"}});expect(changed.commandResult.resultCode).toBe("idempotency_key_reused");
    const duplicate=await exec(db,env(first.bootstrap,"create_staff","64000000-0000-4000-8000-000000000011",staff));expect(duplicate.commandResult.resultCode).toBe("duplicate_staff_identifier");
    await resetTenantDatabaseRole(db);const rows=await db.query<{external_staff_id:string;pin_hash:string|null;kiosk_enabled:boolean;onboarding_attendance_eligible:boolean;assignments:number}>(`select p.external_staff_id,k.pin_hash,k.kiosk_enabled,k.onboarding_attendance_eligible,(select count(*)::int from public.staff_site_assignments a where a.staff_id=p.id) assignments from public.staff_profiles p join public.staff_kiosk_settings k on k.staff_id=p.id where p.organisation_id=$1`,[s.session.organisationId]);
    expect(rows.rows).toEqual([{external_staff_id:"EMP-001",pin_hash:null,kiosk_enabled:false,onboarding_attendance_eligible:true,assignments:1}]);expect((await db.query<{state:string;trial_started_at:string|null;trial_ends_at:string|null}>(`select state,trial_started_at,trial_ends_at from public.organisation_subscriptions where organisation_id=$1 and is_current`,[s.session.organisationId])).rows).toEqual([{state:"trial_pending",trial_started_at:null,trial_ends_at:null}]);});
  it("stages rows without operational writes, permits explicit exclusion, then imports the reviewed set atomically",async()=>{const s=await ready(db);const staged=await exec(db,env(s,"preview_staff_import","64000000-0000-4000-8000-000000000020",{safeFilename:"fictional.csv",fileDigest:"a".repeat(64),rows:[{sourceRowNumber:2,externalStaffId:"EMP-101",fullName:"Jamie Patel",displayName:"Jamie",email:"",employmentStatus:"active",startDate:"2026-09-01",jobRole:"staff",siteName:"",attendanceEligible:false},{sourceRowNumber:3,externalStaffId:"",fullName:"Casey Taylor",displayName:"Casey",email:"",employmentStatus:"active",startDate:"2026-09-01",jobRole:"staff",siteName:"",attendanceEligible:false}]}));
    expect(staged.bootstrap.staffing.activeStaffCount).toBe(0);const batch=staged.bootstrap.staffing.activeBatch!;expect(batch.rows).toHaveLength(2);const invalid=batch.rows.find(r=>r.validationCodes.length)!;
    await setTenantAuthUser(db,USER_B_OWNER,"aal2");await expect(db.query(`select id from public.staff_import_batches where id=$1`,[batch.id])).rejects.toThrow(/permission denied/);await setTenantAuthUser(db,USER_A_OWNER,"aal2");
    const reviewed=await exec(db,env(staged.bootstrap,"review_staff_import_row","64000000-0000-4000-8000-000000000021",{batchId:batch.id,rowId:invalid.id,decision:"exclude"}));
    const reviewedSetHash=reviewedHash(reviewed.bootstrap.staffing.activeBatch!.rows);
    const changedSet=await exec(db,env(reviewed.bootstrap,"commit_staff_import","64000000-0000-4000-8000-000000000022",{batchId:batch.id,reviewedSetHash:"f".repeat(64)}));expect(changedSet.commandResult.resultCode).toBe("reviewed_set_changed");
    const committed=await exec(db,env(reviewed.bootstrap,"commit_staff_import","64000000-0000-4000-8000-000000000023",{batchId:batch.id,reviewedSetHash}));expect(committed.commandResult.resultCode).toBe("staff_import_committed");expect(committed.bootstrap.staffing.activeStaffCount).toBe(1);const changedRetry=await exec(db,env(committed.bootstrap,"commit_staff_import","64000000-0000-4000-8000-000000000024",{batchId:batch.id,reviewedSetHash:"d".repeat(64)}));expect(changedRetry.commandResult.resultCode).toBe("reviewed_set_changed");const retried=await exec(db,env(committed.bootstrap,"commit_staff_import","64000000-0000-4000-8000-000000000025",{batchId:batch.id,reviewedSetHash}));expect(retried.commandResult.outcome).toBe("replayed");expect(retried.bootstrap.staffing.activeStaffCount).toBe(1);});
  it("rejects AAL1, stale and cross-user access without staff writes",async()=>{const s=await ready(db);const staff={externalStaffId:"E1",fullName:"Alex Morgan",displayName:"Alex",employmentStatus:"active",startDate:"2026-09-01",jobRole:"staff",attendanceEligible:false};await setTenantAuthUser(db,USER_A_OWNER,"aal1");expect((await exec(db,env(s,"create_staff","64000000-0000-4000-8000-000000000030",staff))).commandResult.resultCode).toBe("mfa_required");
    await setTenantAuthUser(db,USER_A_OWNER,"aal2");const stale={...env(s,"create_staff","64000000-0000-4000-8000-000000000032",staff),expectedSessionRevision:String(BigInt(s.session.revision)-BigInt(1))};expect((await exec(db,stale)).commandResult.resultCode).toBe("stale_session_revision");
    await setTenantAuthUser(db,USER_B_OWNER,"aal2");expect((await exec(db,env(s,"skip_staffing","64000000-0000-4000-8000-000000000031",{acknowledgement:"staffing_not_ready"}))).commandResult.resultCode).toBe("permission_denied");
    await setTenantAuthUser(db,USER_A_OWNER,"aal2");const skipped=await exec(db,env(s,"skip_staffing","64000000-0000-4000-8000-000000000033",{acknowledgement:"staffing_not_ready"}));expect(skipped.bootstrap.steps.find(step=>step.stepKey==="staffing")?.status).toBe("skipped");
    const resumed=await exec(db,env(skipped.bootstrap,"create_staff","64000000-0000-4000-8000-000000000034",staff));expect(resumed.commandResult.resultCode).toBe("staff_manual_created");expect(resumed.bootstrap.steps.find(step=>step.stepKey==="staffing")?.status).toBe("in_progress");});
  it("uses authoritative active usage to deny a plan-limit breach without partial writes",async()=>{const s=await ready(db);const limit=s.staffing.staffLimit!;await resetTenantDatabaseRole(db);await db.query(`insert into public.staff_profiles(id,organisation_id,full_name,display_name,employment_role,active) select 'capacity_'||n,$1,'Fictional Person '||n,'Person '||n,'staff',true from generate_series(1,$2::int)n`,[s.session.organisationId,limit]);await setTenantAuthUser(db,USER_A_OWNER,"aal2");
    const result=await exec(db,env(s,"create_staff","64000000-0000-4000-8000-000000000040",{externalStaffId:"OVER-1",fullName:"Capacity Example",displayName:"Capacity",employmentStatus:"active",startDate:"2026-09-01",jobRole:"staff",attendanceEligible:true}));expect(result.commandResult.resultCode).toBe("staff_limit_exceeded");await resetTenantDatabaseRole(db);expect((await db.query<{count:number}>(`select count(*)::int count from public.staff_profiles where organisation_id=$1`,[s.session.organisationId])).rows[0].count).toBe(limit);});
  it("rolls back every operational row when an injected import failure occurs",async()=>{const s=await ready(db);const staged=await exec(db,env(s,"preview_staff_import","64000000-0000-4000-8000-000000000050",{safeFilename:"atomic.csv",fileDigest:"c".repeat(64),rows:[{sourceRowNumber:2,externalStaffId:"EMP-201",fullName:"Taylor Example",displayName:"Taylor",email:"",employmentStatus:"active",startDate:"2026-09-01",jobRole:"staff",siteName:"",attendanceEligible:true},{sourceRowNumber:3,externalStaffId:"EMP-202",fullName:"Jordan Example",displayName:"Jordan",email:"",employmentStatus:"active",startDate:"2026-09-01",jobRole:"staff",siteName:"",attendanceEligible:true}]}));const batch=staged.bootstrap.staffing.activeBatch!;const command=env(staged.bootstrap,"commit_staff_import","64000000-0000-4000-8000-000000000051",{batchId:batch.id,reviewedSetHash:reviewedHash(batch.rows)});
    await resetTenantDatabaseRole(db);await db.exec(`create function private.fail_second_staff() returns trigger language plpgsql as $$begin if new.external_staff_id='EMP-202' then raise exception 'injected import failure';end if;return new;end$$;create trigger fail_second_staff before insert on public.staff_profiles for each row execute function private.fail_second_staff();`);await setTenantAuthUser(db,USER_A_OWNER,"aal2");await expect(exec(db,command)).rejects.toThrow(/injected import failure/);await resetTenantDatabaseRole(db);expect((await db.query<{count:number}>(`select count(*)::int count from public.staff_profiles where organisation_id=$1`,[s.session.organisationId])).rows[0].count).toBe(0);await db.exec(`drop trigger fail_second_staff on public.staff_profiles;drop function private.fail_second_staff()`);await setTenantAuthUser(db,USER_A_OWNER,"aal2");expect((await exec(db,command)).commandResult.resultCode).toBe("staff_import_committed");});
  it("rejects ambiguous or historical assignment dates at the database boundary",async()=>{const s=await ready(db);const base={externalStaffId:"DATE-1",fullName:"Date Example",displayName:"Date",employmentStatus:"active",jobRole:"staff",attendanceEligible:true};expect((await exec(db,env(s,"create_staff","64000000-0000-4000-8000-000000000060",{...base,startDate:"01/02/2026"}))).commandResult.resultCode).toBe("invalid_start_date");expect((await exec(db,env(s,"create_staff","64000000-0000-4000-8000-000000000061",{...base,startDate:"2020-01-01"}))).commandResult.resultCode).toBe("invalid_assignment_dates");});
  it("redacts expired staged PII and presents a re-upload state",async()=>{const s=await ready(db);const staged=await exec(db,env(s,"preview_staff_import","64000000-0000-4000-8000-000000000070",{safeFilename:"expiry.csv",fileDigest:"e".repeat(64),rows:[{sourceRowNumber:2,externalStaffId:"EXP-1",fullName:"Expiry Example",displayName:"Expiry",email:"expiry@example.invalid",employmentStatus:"active",startDate:"2026-09-01",jobRole:"staff",siteName:"",attendanceEligible:false}]}));const batch=staged.bootstrap.staffing.activeBatch!;await resetTenantDatabaseRole(db);await db.query(`update public.staff_import_batches set expires_at=now()-interval '1 minute' where id=$1`,[batch.id]);await setTenantAuthUser(db,USER_A_OWNER,"aal2");const expired=await load(db);expect(expired.staffing.activeBatch?.status).toBe("expired");expect(expired.staffing.activeBatch?.rows).toEqual([]);await resetTenantDatabaseRole(db);const redacted=(await db.query<{normalised_data:unknown;redacted_at:Date|null}>(`select normalised_data,redacted_at from public.staff_import_rows where batch_id=$1`,[batch.id])).rows[0];expect(redacted.normalised_data).toEqual({});expect(redacted.redacted_at).toBeInstanceOf(Date);});
});
