"use client";

import { useActionState, useEffect, useState } from "react";
import { useRouter } from "next/navigation";
import { CheckCircle2, KeyRound, MonitorSmartphone, Radio, ShieldCheck, Wifi } from "lucide-react";
import { Button } from "@/components/ui/primitives";
import { completeKioskSetupAction, mutateKioskRegistrationAction, setKioskStaffPinAction, startKioskRegistrationAction, type KioskSetupActionState } from "@/lib/onboarding/kiosk-actions";
import type { KioskOnboardingSnapshot } from "@/lib/onboarding/kiosk-contracts";
import { OnboardingNotice } from "./onboarding-shell";

const initial: KioskSetupActionState = { ok: false, code: "", message: "" };
function Hidden({ revision, id }: { revision: string; id: string }) { return <><input type="hidden" name="expectedSessionRevision" value={revision}/><input type="hidden" name="idempotencyKey" value={id}/></>; }
function RegistrationCountdown({ expiresAt }: { expiresAt: string }) {
  const [seconds, setSeconds] = useState(() => Math.max(0, Math.floor((new Date(expiresAt).getTime() - Date.now()) / 1000)));
  useEffect(() => { if (!seconds) return; const timer = window.setInterval(() => setSeconds((value) => Math.max(0, value - 1)), 1000); return () => window.clearInterval(timer); }, [seconds]);
  return <>Expires in {Math.floor(seconds / 60)}:{String(seconds % 60).padStart(2, "0")}.</>;
}

export function KioskSetup({ snapshot, revision, keys }: { snapshot: KioskOnboardingSnapshot; revision: string; keys: string[] }) {
  const [registration, registrationAction, registrationPending] = useActionState(startKioskRegistrationAction, initial);
  const [mutation, mutationAction, mutationPending] = useActionState(mutateKioskRegistrationAction, initial);
  const [pinState, pinAction, pinPending] = useActionState(setKioskStaffPinAction, initial);
  const router = useRouter();
  useEffect(() => { if (snapshot.device?.status === "connected" || !snapshot.registration || snapshot.registration.status === "expired") return; const timer = window.setInterval(() => router.refresh(), 5000); return () => window.clearInterval(timer); }, [router, snapshot.device?.status, snapshot.registration]);
  const activeCode = mutation.oneTimeRegistrationCode ?? registration.oneTimeRegistrationCode;
  const activeExpiry = mutation.registrationExpiresAt ?? registration.registrationExpiresAt;
  const registrationId = mutation.registrationId ?? registration.registrationId ?? snapshot.registration?.registrationId;
  return <div className="kiosk-onboarding">
    <section className="kiosk-setup-safety"><ShieldCheck aria-hidden/><div><h2>Online setup only</h2><p>This device stays in Pre-live mode. It cannot record attendance until your organisation goes live, and offline attendance remains disabled.</p></div></section>
    <div className="kiosk-setup-grid">
      <section className="kiosk-setup-panel" aria-labelledby="prepare-device"><div className="kiosk-setup-panel__number">1</div><div><h2 id="prepare-device">Prepare your clocking device</h2><p>Use a tablet on reliable Wi-Fi. Keep it powered and open the registration page shown below.</p><ul><li><Wifi aria-hidden/>Connect to reliable Wi-Fi</li><li><MonitorSmartphone aria-hidden/>Open <strong>/kiosk/register</strong> on the tablet</li><li><Radio aria-hidden/>Keep this page open while the tablet connects</li></ul></div></section>
      <section className="kiosk-setup-panel" aria-labelledby="register-device"><div className="kiosk-setup-panel__number">2</div><div><h2 id="register-device">Create a one-time registration code</h2><form action={registrationAction} className="kiosk-registration-form"><Hidden revision={revision} id={keys[0]}/><label>Location<select name="siteId" defaultValue={snapshot.registration?.siteId ?? snapshot.availableSites[0]?.siteId} required>{snapshot.availableSites.map((site) => <option key={site.siteId} value={site.siteId}>{site.displayName}</option>)}</select></label><label>Device name<input name="deviceName" minLength={3} maxLength={100} placeholder="Reception tablet" defaultValue={snapshot.registration?.deviceName ?? ""} required/></label><Button disabled={registrationPending}>{registrationPending ? "Creating secure code..." : "Create registration code"}</Button></form>{registration.message ? <OnboardingNotice tone={registration.ok ? "success" : "error"}>{registration.message}</OnboardingNotice> : null}{activeCode && registrationId && activeExpiry ? <div className="kiosk-code" role="status"><span>One-time code</span><strong aria-label={`Registration code ${activeCode}`}>{activeCode.match(/.{1,4}/g)?.join(" ")}</strong><p><RegistrationCountdown key={activeExpiry} expiresAt={activeExpiry}/> This code will not be shown again after you leave.</p><a href={`/kiosk/register?id=${encodeURIComponent(registrationId)}`} target="_blank" rel="noreferrer">Open the registration page</a></div> : null}</div></section>
      <section className="kiosk-setup-panel" aria-labelledby="connection-state"><div className="kiosk-setup-panel__number">3</div><div><h2 id="connection-state">Connection</h2><div className={`kiosk-connection kiosk-connection--${snapshot.device?.status ?? "waiting"}`}><span><Wifi aria-hidden/></span><div><strong>{snapshot.device?.status === "connected" ? "Connected" : snapshot.device?.status === "connection_problem" ? "Connection problem" : snapshot.device?.status === "revoked" ? "Revoked" : "Waiting for device"}</strong><p>{snapshot.device?.lastSeenAt ? `Last seen ${new Intl.DateTimeFormat("en-GB", { dateStyle: "medium", timeStyle: "short", timeZone: "Europe/London" }).format(new Date(snapshot.device.lastSeenAt))}` : "Enter the code on the clocking device to continue."}</p></div></div>{snapshot.registration && ["pending", "claimed", "verified"].includes(snapshot.registration.status) ? <form action={mutationAction} className="kiosk-device-controls"><Hidden revision={revision} id={keys.at(-3)!}/><input type="hidden" name="registrationId" value={snapshot.registration.registrationId}/><Button name="intent" value="replace" variant="secondary" disabled={mutationPending}>{snapshot.device ? "Replace this device" : "Create a replacement code"}</Button><Button name="intent" value="revoke" variant="secondary" disabled={mutationPending}>Revoke access</Button></form> : null}{mutation.message ? <OnboardingNotice tone={mutation.ok ? "success" : "error"}>{mutation.message}</OnboardingNotice> : null}</div></section>
    </div>
    <section className="kiosk-staff-readiness" aria-labelledby="staff-ready"><div><span>Staff readiness</span><h2 id="staff-ready">{snapshot.readiness.pinReadyStaffCount} of {snapshot.readiness.eligibleStaffCount} ready to clock</h2><p>PINs are stored securely and never shown here after saving.</p></div><ul>{snapshot.staff.map((staff, index) => <li key={staff.staffId}><div><strong>{staff.displayName}</strong><span>{staff.siteAssigned ? "Site assigned" : "Site needed"} · {staff.attendanceEligible ? "Attendance eligible" : "Not eligible"}</span></div>{staff.pinReady ? <span className="kiosk-ready"><CheckCircle2 aria-hidden/>PIN ready</span> : <form action={pinAction} className="kiosk-pin-form"><Hidden revision={revision} id={keys[index + 1]}/><input type="hidden" name="staffId" value={staff.staffId}/><label><span className="sr-only">Temporary PIN for {staff.displayName}</span><KeyRound aria-hidden/><input name="temporaryPin" inputMode="numeric" pattern="[0-9]{4,6}" minLength={4} maxLength={6} autoComplete="new-password" placeholder="Secure PIN" required/></label><Button disabled={pinPending} variant="secondary">Set PIN</Button></form>}</li>)}</ul>{pinState.message ? <OnboardingNotice tone={pinState.ok ? "success" : "error"}>{pinState.message}</OnboardingNotice> : null}</section>
    {snapshot.readiness.complete ? <><section className="kiosk-setup-complete"><CheckCircle2 aria-hidden/><div><h2>Your clocking device is ready</h2><p>Attendance will become available when setup goes live.</p></div></section><form action={completeKioskSetupAction} className="kiosk-complete-action"><Hidden revision={revision} id={keys.at(-1)!}/><Button>Complete clocking device setup</Button></form></> : null}
  </div>;
}
