-- Commercial Workstream 7F: ordinary staff invitations and account linking only.
-- Kiosk registration, readiness, Go Live, trial activation and offline authority remain excluded.

alter table public.organisation_invitations
  drop constraint if exists organisation_invitations_invitation_kind_check;
alter table public.organisation_invitations
  add constraint organisation_invitations_invitation_kind_check check(invitation_kind in('legacy','manager','staff'));
alter table public.organisation_invitations
  add column if not exists staff_id text,
  add constraint organisation_invitations_staff_fk foreign key(organisation_id,staff_id)
    references public.staff_profiles(organisation_id,id) on delete restrict,
  add constraint organisation_invitations_kind_staff_check check(
    (invitation_kind='staff' and staff_id is not null and template_version='staff_invitation_v1')
    or (invitation_kind<>'staff' and staff_id is null));
create unique index organisation_invitations_pending_staff_key on public.organisation_invitations(organisation_id,staff_id)
  where invitation_kind='staff' and status='pending';
create unique index organisation_memberships_staff_link_key on public.organisation_memberships(organisation_id,staff_id)
  where staff_id is not null and status in('active','suspended','invited');

alter table public.message_outbox drop constraint if exists message_outbox_message_type_check;
alter table public.message_outbox add constraint message_outbox_message_type_check check(message_type in('manager_invitation','staff_invitation'));
alter table public.message_outbox drop constraint if exists message_outbox_template_version_check;
alter table public.message_outbox add constraint message_outbox_template_version_check check(template_version in('manager_invitation_v1','staff_invitation_v1'));

create table public.staff_invitation_audit_events(
  id uuid primary key default gen_random_uuid(), organisation_id uuid not null references public.organisations(id) on delete restrict,
  invitation_id uuid not null, staff_id text not null, event_type text not null check(event_type in('created','delivery_failed','resent','revoked','accepted')),
  actor_auth_user_id uuid, actor_membership_id uuid, request_id uuid, safe_metadata jsonb not null default '{}'::jsonb
    check(not(safe_metadata::text~*'(email|token|password|secret|pin|address|name)')), created_at timestamptz not null default now(),
  foreign key(organisation_id,invitation_id) references public.organisation_invitations(organisation_id,id) on delete restrict,
  foreign key(organisation_id,staff_id) references public.staff_profiles(organisation_id,id) on delete restrict,
  foreign key(organisation_id,actor_membership_id) references public.organisation_memberships(organisation_id,id) on delete restrict);
alter table public.staff_invitation_audit_events enable row level security;
revoke all on public.staff_invitation_audit_events from public,anon,authenticated;
grant select on public.staff_invitation_audit_events to authenticated;
create policy staff_invitation_audit_select on public.staff_invitation_audit_events for select to authenticated
  using(private.has_permission(organisation_id,'organisation.audit.read'));

alter table public.onboarding_command_receipts drop constraint onboarding_command_receipts_command_type_check;
alter table public.onboarding_command_receipts add constraint onboarding_command_receipts_command_type_check check(command_type in(
  'save_step_draft','accept_legal_documents','complete_owner_setup','create_organisation','create_first_site','select_plan','save_settings',
  'save_staff_draft','create_staff','preview_staff_import','review_staff_import_row','commit_staff_import','complete_staffing','skip_staffing',
  'create_manager_invitation','resend_manager_invitation','revoke_manager_invitation','acknowledge_sole_manager','complete_manager_invitation_step',
  'create_staff_invitations','resend_staff_invitation','revoke_staff_invitation','skip_staff_invitation_step','complete_staff_invitation_step',
  'start_kiosk_registration','confirm_kiosk_connection','evaluate_readiness','go_live'));
alter table public.onboarding_events drop constraint onboarding_events_event_type_check;
alter table public.onboarding_events add constraint onboarding_events_event_type_check check(event_type in(
  'workflow_started','onboarding_started','signup_started','owner_email_verified','owner_mfa_enrolled','owner_mfa_ready','owner_security_completed','legal_acceptance_completed',
  'organisation_creation_started','organisation_created','first_site_started','first_site_validation_failed','first_site_defaults_created','first_site_created',
  'plan_selection_started','plan_selected','trial_selected','trial_pending_created','subscription_step_completed','trial_activated','settings_completed',
  'staff_import_started','staffing_started','staff_manual_created','staff_import_uploaded','staff_import_validated','staff_import_reviewed','staff_import_committed','staffing_skipped','staffing_completed',
  'manager_invitation_step_started','manager_invitation_created','manager_invitation_delivery_failed','manager_invitation_resent','manager_invitation_revoked','manager_invitation_accepted','sole_manager_acknowledged','manager_invitation_step_completed',
  'staff_invitation_step_started','staff_invitation_created','staff_invitation_delivery_failed','staff_invitation_resent','staff_invitation_revoked','staff_invitation_accepted','staff_invitation_step_skipped','staff_invitation_step_completed',
  'kiosk_registration_started','kiosk_connected','readiness_evaluated','go_live_blocked','go_live_completed','workflow_abandoned'));

create or replace function private.can_grant_staff_access(target_organisation_id uuid,target_membership_id uuid,target_staff_id text)
returns boolean language sql stable security definer set search_path='' as $$
  select exists(select 1 from public.organisation_memberships m join public.membership_role_assignments r
    on r.organisation_id=m.organisation_id and r.membership_id=m.id and r.revoked_at is null
    where m.organisation_id=target_organisation_id and m.id=target_membership_id and m.status='active' and (
      r.scope_type='organisation' and r.role in('organisation_owner','organisation_admin','hr_admin')
      or r.scope_type='site' and r.role='site_manager' and not exists(
        select 1 from public.staff_site_assignments a left join public.membership_site_access x
          on x.organisation_id=a.organisation_id and x.membership_id=m.id and x.site_id=a.site_id and x.revoked_at is null
        where a.organisation_id=target_organisation_id and a.staff_id=target_staff_id
          and (a.effective_to is null or a.effective_to>=current_date) and x.id is null)));
$$;

create or replace function private.staff_invitation_snapshot(target_session_id uuid)
returns jsonb language sql stable security definer set search_path='' as $$
  select jsonb_build_object('skipped',coalesce((select status='skipped' from public.onboarding_step_states where session_id=target_session_id and step_key='staff_invitations'),false),
    'staff',coalesce((select jsonb_agg(jsonb_build_object(
      'staffId',p.id,'displayName',p.display_name,
      'maskedEmail',case when p.email is null or btrim(p.email)='' then null else left(lower(p.email),1)||'***@'||split_part(lower(p.email),'@',2) end,
      'siteIds',coalesce((select jsonb_agg(distinct a.site_id order by a.site_id) from public.staff_site_assignments a join public.organisation_sites site on site.id=a.site_id and site.organisation_id=a.organisation_id and site.active and site.archived_at is null where a.organisation_id=p.organisation_id and a.staff_id=p.id and (a.effective_to is null or a.effective_to>=current_date)),'[]'::jsonb),
      'accountState',case when m.id is not null then 'account_linked' when p.email is null or btrim(p.email)='' then 'pin_only'
        when i.status='pending' and o.delivery_status in('retryable_failure','permanent_failure') then 'delivery_failed'
        when i.status='pending' and i.expires_at<=now() then 'invitation_expired' when i.status='pending' then 'invitation_pending'
        when i.status='expired' then 'invitation_expired' else 'no_account' end,
      'invitationId',i.id,'invitationStatus',case when i.status='pending' and i.expires_at<=now() then 'expired' else i.status::text end,
      'deliveryStatus',case when o.delivery_status='processing' then 'queued' else o.delivery_status end,
      'attendanceMode',case when p.email is null or btrim(p.email)='' then 'pin_only' else 'account_optional' end) order by p.display_name,p.id)
      from public.onboarding_sessions s join public.staff_profiles p on p.organisation_id=s.organisation_id and p.active
      left join public.organisation_memberships m on m.organisation_id=p.organisation_id and m.staff_id=p.id and m.status in('active','suspended')
      left join lateral(select x.* from public.organisation_invitations x where x.organisation_id=p.organisation_id and x.staff_id=p.id and x.invitation_kind='staff' order by x.created_at desc limit 1)i on true
      left join lateral(select x.delivery_status from public.message_outbox x where x.invitation_id=i.id order by x.created_at desc limit 1)o on true
      where s.id=target_session_id),'[]'::jsonb));
$$;

alter function private.commercial_onboarding_snapshot(uuid) rename to commercial_onboarding_snapshot_7e;
alter function public.get_or_create_onboarding_bootstrap() rename to get_or_create_onboarding_bootstrap_7e;
alter function public.get_or_create_onboarding_bootstrap_7e() set schema private;
alter function public.execute_onboarding_bootstrap_command(jsonb) rename to execute_onboarding_bootstrap_command_7e;
alter function public.execute_onboarding_bootstrap_command_7e(jsonb) set schema private;

create or replace function private.commercial_onboarding_snapshot(target_session_id uuid)
returns jsonb language sql stable security definer set search_path='' as $$
  select private.commercial_onboarding_snapshot_7e(target_session_id)||jsonb_build_object(
    'steps',coalesce((select jsonb_agg(jsonb_build_object('stepKey',step_key,'status',status,'revision',revision::text,'draftPayload',draft_payload,'validationSummary',validation_summary)
      order by case step_key when 'owner_security' then 1 when 'legal_acceptance' then 2 when 'organisation' then 3 when 'first_site' then 4 when 'subscription' then 5 when 'staffing' then 6 when 'manager_invitations' then 7 when 'staff_invitations' then 8 else 99 end)
      from public.onboarding_step_states where session_id=target_session_id and step_key in('owner_security','legal_acceptance','organisation','first_site','subscription','staffing','manager_invitations','staff_invitations')),'[]'::jsonb),
    'staffInvitations',private.staff_invitation_snapshot(target_session_id));
$$;

create or replace function public.get_or_create_onboarding_bootstrap()
returns jsonb language plpgsql security definer set search_path='' as $$
declare initial jsonb;target_id uuid;target_organisation_id uuid;released uuid[];
begin initial:=private.get_or_create_onboarding_bootstrap_7e();target_id:=(initial->'session'->>'id')::uuid;
  select organisation_id into target_organisation_id from public.onboarding_sessions where id=target_id;
  insert into public.onboarding_step_states(session_id,organisation_id,step_key,step_version,status,revision)
    select id,organisation_id,'staff_invitations',1,'not_started',0 from public.onboarding_sessions where id=target_id on conflict(session_id,step_key) do nothing;
  select array_agg(o.delivery_secret_id) into released from public.message_outbox o join public.organisation_invitations i on i.id=o.invitation_id where i.organisation_id=target_organisation_id and i.invitation_kind='staff' and i.status='pending' and i.expires_at<=now() and o.delivery_secret_id is not null;
  update public.message_outbox o set delivery_status='permanent_failure',failed_at=coalesce(failed_at,now()),last_error_code='invitation_expired',delivery_secret_id=null from public.organisation_invitations i where i.id=o.invitation_id and i.organisation_id=target_organisation_id and i.invitation_kind='staff' and i.status='pending' and i.expires_at<=now() and o.delivery_status in('queued','processing','retryable_failure');
  update public.organisation_invitations set status='expired' where organisation_id=target_organisation_id and invitation_kind='staff' and status='pending' and expires_at<=now();
  delete from vault.secrets where id=any(coalesce(released,'{}'::uuid[]));return private.commercial_onboarding_snapshot(target_id);end$$;

create or replace function private.execute_staff_invitation_command(command_envelope jsonb)
returns jsonb language plpgsql security definer set search_path='' as $$
#variable_conflict use_variable
declare session_row public.onboarding_sessions%rowtype;member public.organisation_memberships%rowtype;receipt public.onboarding_command_receipts%rowtype;existing public.onboarding_command_receipts%rowtype;
  payload jsonb:=command_envelope->'payload';command_type text:=command_envelope->>'commandType';key_value uuid;expected_revision bigint;hash_value text;result_code text;issues jsonb:='[]';reference jsonb:='{}';event_name text;lifetime_days int:=7;
  staff_value jsonb;target_staff public.staff_profiles%rowtype;invitation public.organisation_invitations%rowtype;new_invitation public.organisation_invitations%rowtype;raw_token text;secret_id uuid;released uuid[];created_ids uuid[]:='{}';expected_hash text;
begin
  if auth.uid() is null then raise exception 'authentication required' using errcode='42501';end if;
  if jsonb_typeof(command_envelope)<>'object' or jsonb_typeof(payload)<>'object' or command_envelope->>'schemaVersion'<>'1' or command_envelope->>'workflowKey'<>'commercial_customer_v1' or command_envelope->>'workflowVersion'<>'1' or not((command_envelope->>'sessionId')~*'^[0-9a-f-]{36}$') or not((command_envelope->>'idempotencyKey')~*'^[0-9a-f-]{36}$') or not((command_envelope->>'expectedSessionRevision')~'^(0|[1-9][0-9]*)$') then raise exception 'invalid onboarding command envelope' using errcode='22023';end if;
  key_value:=(command_envelope->>'idempotencyKey')::uuid;expected_revision:=(command_envelope->>'expectedSessionRevision')::bigint;hash_value:=private.onboarding_request_digest(command_envelope);
  select * into session_row from public.onboarding_sessions where id=(command_envelope->>'sessionId')::uuid for update;
  if not found or session_row.owner_auth_user_id<>auth.uid() or session_row.organisation_id is null then result_code:='permission_denied';end if;
  if result_code is null then select * into member from public.organisation_memberships where organisation_id=session_row.organisation_id and auth_user_id=auth.uid() and status='active' for update;if not found or not private.has_permission(session_row.organisation_id,'membership.manage') then result_code:='permission_denied';end if;end if;
  if result_code is null and coalesce(auth.jwt()->>'aal','aal1')<>'aal2' then result_code:='mfa_required';end if;
  if result_code is null and session_row.revision<>expected_revision then result_code:='stale_session_revision';end if;
  select * into existing from public.onboarding_command_receipts where session_id=session_row.id and command_type=command_type and idempotency_key=key_value;
  if found then if result_code in('permission_denied','mfa_required') then return private.onboarding_command_response(command_envelope,'permission_denied','not_saved',result_code,'{}',session_row.revision,'[]',null)||jsonb_build_object('bootstrap',null);end if;
    if existing.request_hash<>hash_value then result_code:='idempotency_key_reused';elsif existing.status in('succeeded','failed_final') then return private.onboarding_command_response(command_envelope,case when existing.status='succeeded' then 'replayed' else existing.result_outcome end,existing.result_data_state,existing.result_code,coalesce(existing.result_reference,'{}'),existing.result_session_revision,coalesce(existing.result_issues,'[]'),coalesce(existing.result_readiness,private.onboarding_foundation_readiness(session_row.id,existing.id)))||jsonb_build_object('bootstrap',private.commercial_onboarding_snapshot(session_row.id));end if;end if;
  if existing.id is null then insert into public.onboarding_command_receipts(session_id,organisation_id,command_type,idempotency_key,request_hash,status) values(session_row.id,session_row.organisation_id,command_type,key_value,hash_value,'processing') returning * into receipt;else receipt:=existing;end if;
  select manager_invitation_lifetime_days into lifetime_days from public.organisation_settings where organisation_id=session_row.organisation_id;

  if result_code is null and command_type='create_staff_invitations' then
    if (select count(*) from jsonb_object_keys(payload))<>2 or not(payload?'staffIds' and payload?'reviewedSetHash') or jsonb_typeof(payload->'staffIds')<>'array' or jsonb_array_length(payload->'staffIds') not between 1 and 250 or payload->>'reviewedSetHash'!~'^[a-f0-9]{64}$' or (select count(*) from jsonb_array_elements_text(payload->'staffIds'))<>(select count(distinct value) from jsonb_array_elements_text(payload->'staffIds')) then result_code:='invalid_staff_invitation_payload';end if;
    if result_code is null then select encode(sha256(convert_to(string_agg(value,E'\n' order by value),'UTF8')),'hex') into expected_hash from jsonb_array_elements_text(payload->'staffIds');if expected_hash<>payload->>'reviewedSetHash' then result_code:='reviewed_set_changed';end if;end if;
    if result_code is null then for staff_value in select value from jsonb_array_elements(payload->'staffIds') loop
      if jsonb_typeof(staff_value)<>'string' then result_code:='staff_not_eligible';exit;end if;
      select * into target_staff from public.staff_profiles where organisation_id=session_row.organisation_id and id=staff_value#>>'{}' and active for update;
      if not found or target_staff.email is null or lower(btrim(target_staff.email))!~'^[^@[:space:]]+@[^@[:space:]]+\.[^@[:space:]]+$' or not private.can_grant_staff_access(session_row.organisation_id,member.id,target_staff.id)
        or not exists(select 1 from public.staff_site_assignments a join public.organisation_sites site on site.organisation_id=a.organisation_id and site.id=a.site_id and site.active and site.archived_at is null where a.organisation_id=target_staff.organisation_id and a.staff_id=target_staff.id and (a.effective_to is null or a.effective_to>=current_date))
        or exists(select 1 from public.organisation_memberships m where m.organisation_id=target_staff.organisation_id and m.staff_id=target_staff.id and m.status in('active','suspended','invited'))
        or exists(select 1 from public.organisation_invitations i where i.organisation_id=target_staff.organisation_id and (i.staff_id=target_staff.id or i.invited_email=lower(btrim(target_staff.email))) and i.status='pending') then result_code:='staff_not_eligible';exit;end if;
    end loop;end if;
    if result_code is null then for staff_value in select value from jsonb_array_elements(payload->'staffIds') loop select * into target_staff from public.staff_profiles where organisation_id=session_row.organisation_id and id=staff_value#>>'{}' for update;
      raw_token:=encode(extensions.gen_random_bytes(32),'hex');insert into public.organisation_invitations(organisation_id,invited_email,token_hash,status,expires_at,invited_by_membership_id,invitation_kind,template_version,staff_id) values(session_row.organisation_id,lower(btrim(target_staff.email)),sha256(convert_to(raw_token,'UTF8')),'pending',now()+make_interval(days=>coalesce(lifetime_days,7)),member.id,'staff','staff_invitation_v1',target_staff.id) returning * into invitation;
      insert into public.organisation_invitation_roles(organisation_id,invitation_id,role,scope_type,site_id) values(session_row.organisation_id,invitation.id,'staff','organisation',null);
      insert into public.organisation_invitation_site_access(organisation_id,invitation_id,site_id) select distinct a.organisation_id,invitation.id,a.site_id from public.staff_site_assignments a join public.organisation_sites site on site.organisation_id=a.organisation_id and site.id=a.site_id and site.active and site.archived_at is null where a.organisation_id=session_row.organisation_id and a.staff_id=target_staff.id and (a.effective_to is null or a.effective_to>=current_date);
      secret_id:=vault.create_secret(raw_token,'staff-invitation-'||invitation.id::text,'Encrypted delivery material for one staff invitation');insert into public.message_outbox(organisation_id,message_type,recipient_address,invitation_id,template_version,delivery_secret_id,payload,next_attempt_at) values(session_row.organisation_id,'staff_invitation',lower(btrim(target_staff.email)),invitation.id,'staff_invitation_v1',secret_id,jsonb_build_object('invitationId',invitation.id),now());
      insert into public.staff_invitation_audit_events(organisation_id,invitation_id,staff_id,event_type,actor_auth_user_id,actor_membership_id,request_id,safe_metadata) values(session_row.organisation_id,invitation.id,target_staff.id,'created',auth.uid(),member.id,key_value,jsonb_build_object('statusCode','staff_invitation_created'));created_ids:=array_append(created_ids,invitation.id);end loop;
      reference:=jsonb_build_object('invitationIds',to_jsonb(created_ids));event_name:='staff_invitation_created';end if;
  elsif result_code is null and command_type in('resend_staff_invitation','revoke_staff_invitation') then
    if (select count(*) from jsonb_object_keys(payload))<>1 or not(payload?'invitationId') or (payload->>'invitationId')!~*'^[0-9a-f-]{36}$' then result_code:='invalid_staff_invitation_payload';else select * into invitation from public.organisation_invitations where id=(payload->>'invitationId')::uuid and organisation_id=session_row.organisation_id and invitation_kind='staff' for update;if not found or invitation.status in('accepted','superseded') then result_code:='invitation_not_available';end if;end if;
    if result_code is null and not private.can_grant_staff_access(invitation.organisation_id,member.id,invitation.staff_id) then result_code:='authority_changed';end if;
    if result_code is null and command_type='revoke_staff_invitation' then if invitation.status not in('revoked','expired') then update public.organisation_invitations set status='revoked',revoked_at=now(),revoked_by_membership_id=member.id where id=invitation.id;select array_agg(delivery_secret_id) into released from public.message_outbox where invitation_id=invitation.id and delivery_secret_id is not null;update public.message_outbox set delivery_status='permanent_failure',failed_at=now(),delivery_secret_id=null where invitation_id=invitation.id and delivery_status in('queued','processing','retryable_failure');delete from vault.secrets where id=any(coalesce(released,'{}'::uuid[]));end if;event_name:='staff_invitation_revoked';reference:=jsonb_build_object('invitationIds',jsonb_build_array(invitation.id));
    elsif result_code is null then select * into target_staff from public.staff_profiles where organisation_id=invitation.organisation_id and id=invitation.staff_id and active for update;if not found or lower(btrim(target_staff.email))<>invitation.invited_email then result_code:='staff_identity_changed';else raw_token:=encode(extensions.gen_random_bytes(32),'hex');update public.organisation_invitations set status='superseded',superseded_at=now() where id=invitation.id;insert into public.organisation_invitations(organisation_id,invited_email,token_hash,status,expires_at,invited_by_membership_id,invitation_kind,template_version,staff_id,resend_of_invitation_id) values(invitation.organisation_id,invitation.invited_email,sha256(convert_to(raw_token,'UTF8')),'pending',now()+make_interval(days=>coalesce(lifetime_days,7)),member.id,'staff','staff_invitation_v1',invitation.staff_id,invitation.id) returning * into new_invitation;insert into public.organisation_invitation_roles(organisation_id,invitation_id,role,scope_type,site_id) values(invitation.organisation_id,new_invitation.id,'staff','organisation',null);insert into public.organisation_invitation_site_access(organisation_id,invitation_id,site_id) select organisation_id,new_invitation.id,site_id from public.organisation_invitation_site_access where invitation_id=invitation.id;update public.organisation_invitations set superseded_by_invitation_id=new_invitation.id where id=invitation.id;select array_agg(delivery_secret_id) into released from public.message_outbox where invitation_id=invitation.id and delivery_secret_id is not null;update public.message_outbox set delivery_status='permanent_failure',failed_at=now(),delivery_secret_id=null where invitation_id=invitation.id and delivery_status in('queued','processing','retryable_failure');delete from vault.secrets where id=any(coalesce(released,'{}'::uuid[]));secret_id:=vault.create_secret(raw_token,'staff-invitation-'||new_invitation.id::text,'Encrypted delivery material for one staff invitation');insert into public.message_outbox(organisation_id,message_type,recipient_address,invitation_id,template_version,delivery_secret_id,payload,next_attempt_at) values(invitation.organisation_id,'staff_invitation',invitation.invited_email,new_invitation.id,'staff_invitation_v1',secret_id,jsonb_build_object('invitationId',new_invitation.id),now());invitation:=new_invitation;event_name:='staff_invitation_resent';reference:=jsonb_build_object('invitationIds',jsonb_build_array(invitation.id));end if;end if;
  elsif result_code is null and command_type='skip_staff_invitation_step' then if payload<>jsonb_build_object('acknowledgement','invite_staff_later') then result_code:='skip_acknowledgement_required';else event_name:='staff_invitation_step_skipped';end if;
  elsif result_code is null and command_type='complete_staff_invitation_step' then if payload<>'{}'::jsonb then result_code:='invalid_staff_invitation_payload';elsif not exists(select 1 from public.organisation_invitations where organisation_id=session_row.organisation_id and invitation_kind='staff') then result_code:='staff_invitation_decision_required';else event_name:='staff_invitation_step_completed';end if;
  elsif result_code is null then result_code:='unsupported_staff_invitation_command';end if;

  if result_code is not null then issues:=jsonb_build_array(jsonb_build_object('code',result_code,'message',case when result_code='stale_session_revision' then 'Onboarding changed after this page was opened. Reload and try again.' else 'Nothing was saved. Review the staff invitation decision and try again.' end,'fieldPath','[]'::jsonb,'repairRoute','/onboarding/staff-invitations'));update public.onboarding_command_receipts set status='failed_final',result_code=result_code,result_outcome=case when result_code='stale_session_revision' then 'workflow_changed' when result_code in('permission_denied','mfa_required') then 'permission_denied' else 'validation_failed' end,result_data_state='not_saved',result_session_revision=session_row.revision,result_issues=issues,completed_at=now() where id=receipt.id;return private.onboarding_command_response(command_envelope,case when result_code='stale_session_revision' then 'workflow_changed' when result_code in('permission_denied','mfa_required') then 'permission_denied' else 'validation_failed' end,'not_saved',result_code,'{}',session_row.revision,issues,private.onboarding_foundation_readiness(session_row.id,receipt.id))||jsonb_build_object('bootstrap',case when result_code='permission_denied' then null else private.commercial_onboarding_snapshot(session_row.id) end);end if;
  if event_name in('staff_invitation_step_skipped','staff_invitation_step_completed') then update public.onboarding_step_states set status=case when event_name='staff_invitation_step_skipped' then 'skipped' else 'complete' end,revision=revision+1,started_at=coalesce(started_at,now()),completed_at=now(),last_saved_at=now(),completed_by_auth_user_id=auth.uid() where session_id=session_row.id and step_key='staff_invitations';update public.onboarding_sessions set current_step_key='kiosk',revision=revision+1,last_activity_at=now() where id=session_row.id returning * into session_row;else update public.onboarding_step_states set status='in_progress',revision=revision+1,started_at=coalesce(started_at,now()),last_saved_at=now(),completed_at=null where session_id=session_row.id and step_key='staff_invitations';update public.onboarding_sessions set current_step_key='staff_invitations',revision=revision+1,last_activity_at=now() where id=session_row.id returning * into session_row;end if;
  if invitation.id is not null and event_name in('staff_invitation_resent','staff_invitation_revoked') then insert into public.staff_invitation_audit_events(organisation_id,invitation_id,staff_id,event_type,actor_auth_user_id,actor_membership_id,request_id,safe_metadata) values(session_row.organisation_id,invitation.id,invitation.staff_id,case when event_name='staff_invitation_resent' then 'resent' else 'revoked' end,auth.uid(),member.id,key_value,jsonb_build_object('statusCode',event_name));end if;
  insert into public.onboarding_events(session_id,organisation_id,event_type,step_key,actor_type,actor_auth_user_id,actor_membership_id,request_id,workflow_revision,safe_metadata) values(session_row.id,session_row.organisation_id,event_name,'staff_invitations','owner',auth.uid(),member.id,key_value,session_row.revision,jsonb_build_object('statusCode',event_name,'resourceCounts',jsonb_build_object('invitations',coalesce(array_length(created_ids,1),0))));update public.onboarding_command_receipts set status='succeeded',result_code=event_name,result_outcome='succeeded',result_data_state='saved',result_session_revision=session_row.revision,result_reference=reference,result_issues='[]',completed_at=now() where id=receipt.id;return private.onboarding_command_response(command_envelope,'succeeded','saved',event_name,reference,session_row.revision,'[]',private.onboarding_foundation_readiness(session_row.id,receipt.id))||jsonb_build_object('bootstrap',private.commercial_onboarding_snapshot(session_row.id));
end$$;

create or replace function public.execute_onboarding_bootstrap_command(command_envelope jsonb)
returns jsonb language plpgsql security definer set search_path='' as $$begin if command_envelope->>'commandType' in('create_staff_invitations','resend_staff_invitation','revoke_staff_invitation','skip_staff_invitation_step','complete_staff_invitation_step') then return private.execute_staff_invitation_command(command_envelope);end if;return private.execute_onboarding_bootstrap_command_7e(command_envelope);end$$;

create or replace function public.inspect_staff_invitation(invitation_token text)
returns jsonb language plpgsql stable security definer set search_path='' as $$declare invitation public.organisation_invitations%rowtype;organisation_name text;begin if invitation_token is null or invitation_token!~'^[a-f0-9]{64}$' then return jsonb_build_object('state','unavailable');end if;select * into invitation from public.organisation_invitations where token_hash=sha256(convert_to(invitation_token,'UTF8')) and invitation_kind='staff';if not found then return jsonb_build_object('state','unavailable');end if;select display_name into organisation_name from public.organisations where id=invitation.organisation_id;return jsonb_build_object('state',case when invitation.status='pending' and invitation.expires_at<=now() then 'expired' else invitation.status::text end,'organisationName',organisation_name,'expiresAt',invitation.expires_at,'requiresMfa',false);end$$;

create or replace function public.accept_staff_invitation(invitation_token text)
returns jsonb language plpgsql security definer set search_path='' as $$
declare invitation public.organisation_invitations%rowtype;staff public.staff_profiles%rowtype;current_email text;confirmed timestamptz;member public.organisation_memberships%rowtype;session_id_value uuid;released uuid[];
begin if auth.uid() is null then return jsonb_build_object('outcome','sign_in_required');end if;if invitation_token is null or invitation_token!~'^[a-f0-9]{64}$' then return jsonb_build_object('outcome','unavailable');end if;
  select * into invitation from public.organisation_invitations where token_hash=sha256(convert_to(invitation_token,'UTF8')) and invitation_kind='staff' for update;if not found then return jsonb_build_object('outcome','unavailable');end if;
  select lower(email),email_confirmed_at into current_email,confirmed from auth.users where id=auth.uid();if current_email is null or current_email<>invitation.invited_email then return jsonb_build_object('outcome','unavailable');end if;if confirmed is null then return jsonb_build_object('outcome','email_verification_required');end if;
  if invitation.status='accepted' then if exists(select 1 from public.organisation_memberships where id=invitation.accepted_by_membership_id and auth_user_id=auth.uid() and staff_id=invitation.staff_id) then return jsonb_build_object('outcome','already_linked','organisationId',invitation.organisation_id,'membershipId',invitation.accepted_by_membership_id);end if;return jsonb_build_object('outcome','unavailable');end if;
  if invitation.status in('revoked','superseded','expired') then return jsonb_build_object('outcome',invitation.status::text);end if;if invitation.expires_at<=now() then update public.organisation_invitations set status='expired' where id=invitation.id;return jsonb_build_object('outcome','expired');end if;
  select * into staff from public.staff_profiles where organisation_id=invitation.organisation_id and id=invitation.staff_id and active for update;if not found or lower(btrim(staff.email))<>invitation.invited_email then return jsonb_build_object('outcome','staff_identity_changed');end if;
  if not exists(select 1 from public.organisation_memberships m where m.id=invitation.invited_by_membership_id and m.organisation_id=invitation.organisation_id and m.status='active') or not private.can_grant_staff_access(invitation.organisation_id,invitation.invited_by_membership_id,invitation.staff_id) then return jsonb_build_object('outcome','authority_changed');end if;
  select * into member from public.organisation_memberships where organisation_id=invitation.organisation_id and auth_user_id=auth.uid() for update;if found then if member.status='active' and member.staff_id=invitation.staff_id and exists(select 1 from public.membership_role_assignments where organisation_id=member.organisation_id and membership_id=member.id and role='staff' and revoked_at is null) then return jsonb_build_object('outcome','already_linked','organisationId',member.organisation_id,'membershipId',member.id);end if;return jsonb_build_object('outcome','membership_conflict');end if;
  if exists(select 1 from public.organisation_memberships where organisation_id=invitation.organisation_id and staff_id=invitation.staff_id and status in('active','suspended','invited')) then return jsonb_build_object('outcome','membership_conflict');end if;
  insert into public.organisation_memberships(organisation_id,auth_user_id,staff_id,status,joined_at,created_by_membership_id) values(invitation.organisation_id,auth.uid(),invitation.staff_id,'active',now(),invitation.invited_by_membership_id) returning * into member;
  insert into public.membership_role_assignments(organisation_id,membership_id,role,scope_type,site_id,granted_by_membership_id) values(invitation.organisation_id,member.id,'staff','organisation',null,invitation.invited_by_membership_id);
  insert into public.membership_site_access(organisation_id,membership_id,site_id,granted_by_membership_id) select distinct a.organisation_id,member.id,a.site_id,invitation.invited_by_membership_id from public.staff_site_assignments a join public.organisation_sites site on site.organisation_id=a.organisation_id and site.id=a.site_id and site.active and site.archived_at is null where a.organisation_id=invitation.organisation_id and a.staff_id=invitation.staff_id and (a.effective_to is null or a.effective_to>=current_date);
  update public.organisation_invitations set status='accepted',accepted_by_membership_id=member.id,accepted_at=now() where id=invitation.id;select array_agg(delivery_secret_id) into released from public.message_outbox where invitation_id=invitation.id and delivery_secret_id is not null;update public.message_outbox set delivery_secret_id=null where invitation_id=invitation.id;delete from vault.secrets where id=any(coalesce(released,'{}'::uuid[]));
  insert into public.staff_invitation_audit_events(organisation_id,invitation_id,staff_id,event_type,actor_auth_user_id,actor_membership_id,safe_metadata) values(invitation.organisation_id,invitation.id,invitation.staff_id,'accepted',auth.uid(),member.id,jsonb_build_object('statusCode','accepted'));
  select id into session_id_value from public.onboarding_sessions where organisation_id=invitation.organisation_id order by created_at limit 1;if session_id_value is not null then insert into public.onboarding_events(session_id,organisation_id,event_type,step_key,actor_type,actor_auth_user_id,actor_membership_id,workflow_revision,safe_metadata) select session_id_value,invitation.organisation_id,'staff_invitation_accepted','staff_invitations','member',auth.uid(),member.id,revision,jsonb_build_object('statusCode','accepted') from public.onboarding_sessions where id=session_id_value;end if;
  return jsonb_build_object('outcome','accepted','organisationId',invitation.organisation_id,'membershipId',member.id,'staffId',invitation.staff_id,'authorisationRevision',coalesce(to_jsonb(member)->>'authorisation_revision','0'));
exception when unique_violation or foreign_key_violation then return jsonb_build_object('outcome','membership_conflict');end$$;

create or replace function public.preview_staff_invitation_token(invitation_id_value uuid)
returns jsonb language plpgsql stable security definer set search_path='' as $$declare token text;begin if coalesce(auth.role(),'')<>'service_role' then raise exception 'service role required' using errcode='42501';end if;select s.decrypted_secret into token from public.organisation_invitations i join public.message_outbox o on o.invitation_id=i.id and o.delivery_secret_id is not null join vault.decrypted_secrets s on s.id=o.delivery_secret_id where i.id=invitation_id_value and i.invitation_kind='staff' and i.status='pending' and i.expires_at>now() order by o.created_at desc limit 1;if token is null then return jsonb_build_object('outcome','not_available');end if;return jsonb_build_object('outcome','available','invitationToken',token);end$$;

create or replace function public.claim_staff_invitation_delivery(invitation_id_value uuid)
returns jsonb language plpgsql security definer set search_path='' as $$declare outbox public.message_outbox%rowtype;token text;begin if coalesce(auth.role(),'')<>'service_role' then raise exception 'service role required' using errcode='42501';end if;select o.* into outbox from public.message_outbox o join public.organisation_invitations i on i.id=o.invitation_id and i.invitation_kind='staff' and i.status='pending' and i.expires_at>now() where o.invitation_id=invitation_id_value and (o.delivery_status in('queued','retryable_failure') and coalesce(o.next_attempt_at,now())<=now() or o.delivery_status='processing' and o.last_attempt_at<now()-interval '15 minutes') order by o.created_at desc limit 1 for update of o skip locked;if not found then return jsonb_build_object('outcome','not_available');end if;select decrypted_secret into token from vault.decrypted_secrets where id=outbox.delivery_secret_id;if token is null then return jsonb_build_object('outcome','not_available');end if;update public.message_outbox set delivery_status='processing',last_attempt_at=now() where id=outbox.id;return jsonb_build_object('outcome','claimed','invitationId',outbox.invitation_id,'recipientAddress',outbox.recipient_address,'templateVersion',outbox.template_version,'invitationToken',token,'attemptCount',outbox.retry_count);end$$;

create or replace function public.record_staff_invitation_delivery(invitation_id_value uuid,delivery_outcome text,provider_code text default null)
returns jsonb language plpgsql security definer set search_path='' as $$declare outbox public.message_outbox%rowtype;invitation public.organisation_invitations%rowtype;next_status text;secret_id_value uuid;session_id_value uuid;revision_value bigint;begin if coalesce(auth.role(),'')<>'service_role' then raise exception 'service role required' using errcode='42501';end if;if delivery_outcome not in('sent','retryable_failure','permanent_failure') or provider_code is not null and(length(provider_code)>80 or provider_code!~'^[A-Za-z0-9_.:-]+$') then raise exception 'invalid delivery outcome' using errcode='22023';end if;select o.* into outbox from public.message_outbox o join public.organisation_invitations i on i.id=o.invitation_id and i.invitation_kind='staff' where o.invitation_id=invitation_id_value and o.delivery_status='processing' order by o.created_at desc limit 1 for update of o;if not found then return jsonb_build_object('outcome','not_available');end if;select * into invitation from public.organisation_invitations where id=outbox.invitation_id;secret_id_value:=outbox.delivery_secret_id;next_status:=case when delivery_outcome='retryable_failure' and outbox.retry_count>=4 then 'permanent_failure' else delivery_outcome end;update public.message_outbox set delivery_status=next_status,retry_count=retry_count+1,last_attempt_at=now(),sent_at=case when next_status='sent' then now() else sent_at end,failed_at=case when next_status='permanent_failure' then now() else failed_at end,next_attempt_at=case when next_status='retryable_failure' then now()+make_interval(mins=>least(60,5*(outbox.retry_count+1))) else null end,last_error_code=case when next_status='sent' then null else coalesce(provider_code,'delivery_failed') end,delivery_secret_id=case when next_status in('sent','permanent_failure') then null else delivery_secret_id end where id=outbox.id returning * into outbox;if next_status in('sent','permanent_failure') and secret_id_value is not null then delete from vault.secrets where id=secret_id_value;end if;if next_status<>'sent' then insert into public.staff_invitation_audit_events(organisation_id,invitation_id,staff_id,event_type,safe_metadata) values(outbox.organisation_id,outbox.invitation_id,invitation.staff_id,'delivery_failed',jsonb_build_object('statusCode',next_status,'providerCode',coalesce(provider_code,'delivery_failed')));select id,revision into session_id_value,revision_value from public.onboarding_sessions where organisation_id=outbox.organisation_id order by created_at limit 1;if session_id_value is not null then insert into public.onboarding_events(session_id,organisation_id,event_type,step_key,actor_type,workflow_revision,safe_metadata) values(session_id_value,outbox.organisation_id,'staff_invitation_delivery_failed','staff_invitations','system',revision_value,jsonb_build_object('statusCode',next_status));end if;end if;return jsonb_build_object('outcome',next_status,'attemptCount',outbox.retry_count);end$$;

insert into public.onboarding_step_states(session_id,organisation_id,step_key,step_version,status,revision) select id,organisation_id,'staff_invitations',1,'not_started',0 from public.onboarding_sessions on conflict(session_id,step_key) do nothing;
revoke all on function private.can_grant_staff_access(uuid,uuid,text),private.staff_invitation_snapshot(uuid),private.commercial_onboarding_snapshot_7e(uuid),private.get_or_create_onboarding_bootstrap_7e(),private.execute_onboarding_bootstrap_command_7e(jsonb),private.execute_staff_invitation_command(jsonb) from public,anon,authenticated,service_role;
revoke all on function public.get_or_create_onboarding_bootstrap(),public.execute_onboarding_bootstrap_command(jsonb),public.inspect_staff_invitation(text),public.accept_staff_invitation(text),public.preview_staff_invitation_token(uuid),public.claim_staff_invitation_delivery(uuid),public.record_staff_invitation_delivery(uuid,text,text) from public,anon,authenticated,service_role;
grant execute on function public.get_or_create_onboarding_bootstrap(),public.execute_onboarding_bootstrap_command(jsonb) to authenticated;
grant execute on function public.inspect_staff_invitation(text) to anon,authenticated;
grant execute on function public.accept_staff_invitation(text) to authenticated;
grant execute on function public.preview_staff_invitation_token(uuid) to service_role;
grant execute on function public.claim_staff_invitation_delivery(uuid),public.record_staff_invitation_delivery(uuid,text,text) to service_role;
